version: '3'
services:
  redis:
    image: redis:4-alpine
  django-app:
    build:
      context: ./backend/src
    image: "backend"
    ports:
      - '8000:8000'
  react-app:
    build:
      context: ./frontend/weathergui
    image: "frontend"
    ports:
      - '3000:3000'
