# Generated by Django 2.1.2 on 2019-03-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=120)),
                ('woeid', models.CharField(max_length=50)),
                ('temperature', models.IntegerField(default=0)),
                ('weather_type', models.TextField(default='')),
                ('air_pressure', models.IntegerField(default=0)),
                ('wind_speed', models.IntegerField(default=0)),
                ('humidity', models.IntegerField(default=0)),
                ('image', models.TextField(default='')),
            ],
        ),
    ]
